project:
  type: website
  output-dir: "."

website:
  title: "Niha Yadav"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: files/NihaYadavCV.pdf
        text: CV
      - text: Knowledge Mining
        menu:
          - href: assignment1-km.qmd
            text: Assignment 1
          - href: assignment2-km.qmd
            text: Assignment 2
          - href: assignment3-km.qmd
            text: Assignment 3
          - href: assignment4-km.qmd
            text: Assignment 4
          - href: assignment5-km.qmd
            text: Assignment 5
          - href: KM-Project.qmd
            text: KM Project
      - text: Information Management
        menu:
          - href: assignment1-im.qmd
            text: Assignment 1
          - href: assignment2-im.qmd
            text: Assignment 2
          - href: assignment3-im.qmd
            text: Assignment 3
          - href: assignment4-im.qmd
            text: Assignment 4
          - href: assignment5-im.qmd
            text: Assignment 5
          - href: assignment6-im.qmd
            text: Assignment 6
          - href: assignment7-im.qmd
            text: Assignment 7
          - href: final-im.qmd
            text: Final Project
        - text: Data Visualization
        menu:
          - href: assignment1-dv.qmd
            text: Assignment 1
          - href: assignment2-dv.qmd
            text: Assignment 2
          - href: assignment3-dv.qmd
            text: Assignment 3
format:
  html:
    theme:
      - simplex
      - brand
    css: styles.css
    toc: true
    number-sections: true
    code-fold: true
    code-summary: "Show R Code"

editor: visual
